Реализация ДЗ модуля 4
htmlacademy-ecmascript/1093569-big-trip-16 pull request #8
Opened 2021-12-05 18:14 UTC by DanteDeGrave

2021-12-05 18:15 UTC, DanteDeGrave commented on src/view/site-edit-point-form-view.js
> +export default class SiteEditPointFormView extends SiteEventsItemView {
Тут наследовал не от абстрактного класса, а от класса создания карточки, что бы не копировать методы отработки нажатия на стрелки.

2021-12-05 19:09 UTC, maks88sgt requested changes

2021-12-05 19:09 UTC, maks88sgt commented on src/view/abstract-view.js
> +  _callback = {};
Почему мы используем приватные и защищенные свойства одновременно? С учетом того, что мы юзаем современный js используй # для приватных свойств, как и в других местах. Разнца в том, что _ это просто условность о которой когда-то договорились, а # это действительно приватные свойства

2021-12-05 19:09 UTC, maks88sgt commented on src/view/site-edit-point-form-view.js
> +  setEditSubmitHandler = (callback) => {
Давай использовать setSubmitHandler. Два глагола вместе Edit и Submit сбивают с толку. То же самое с методом editSubmitHandler, звучит как что-то отвечающее и за edit и submit вместе.

2021-12-05 19:09 UTC, maks88sgt commented on src/view/site-events-item-view.js
> +  setEditClickHandler = (callback) => {
То же насчет имен. Я в целом не настаиваю, но подумай об этом.

2021-12-06 06:15 UTC, DanteDeGrave commented on src/view/abstract-view.js
> +  _callback = {};
Тут у детей нужно в эту переменную записать колбэк this._callback.editClick = callback; Если мы у объявим у родителя эту переменную как приватную, то я не смогу ее вызвать через this. Если не сложно подскажи как на практике лучше реализовать данный кейс ?

2021-12-06 06:15 UTC, DanteDeGrave commented on src/view/abstract-view.js
> +  _callback = {};
> 

Тут у детей нужно в эту переменную записать колбэк this._callback.editClick = callback; Если мы у объявим у родителя эту переменную как приватную, то я не смогу ее вызвать через this. Если не сложно подскажи как на практике лучше реализовать данный кейс ?

2021-12-06 14:26 UTC, merged