Module5 task1
htmlacademy-ecmascript/1093569-big-trip-16 pull request #9
Opened 2021-12-13 12:42 UTC by DanteDeGrave

2021-12-14 18:54 UTC, maks88sgt requested changes

2021-12-14 18:54 UTC, maks88sgt commented on src/presenters/event-presenter.js
> +    if (this.#mode === 'DEFAULT') {
Используй ссылку на константу здесь вместо строки

2021-12-14 18:54 UTC, maks88sgt commented on src/presenters/event-presenter.js
> +    if (this.#mode === 'EDITING') {
То же самое.

2021-12-14 18:54 UTC, maks88sgt commented on src/presenters/event-presenter.js
> +    this.#mode = 'EDITING';
То же

2021-12-14 18:54 UTC, maks88sgt commented on src/presenters/event-presenter.js
> +    this.#mode = 'DEFAULT';
То же

2021-12-14 18:54 UTC, maks88sgt commented on src/utils/render.js
> +  if (component === null) {
```suggestion
  if (!component) {
```

2021-12-14 18:54 UTC, maks88sgt commented on src/view/site-info-view.js
> +  const amountTrip = points.reduce((acc, {price}) =>  acc + price, 0);
Вполне допустимо использовать деструктуризацию здесь, но если честно вижу в первый раз. Если тебе так удобнее оставь.

2021-12-14 19:06 UTC, DanteDeGrave commented on src/presenters/event-presenter.js
> +    if (this.#mode === 'DEFAULT') {
fixed

2021-12-14 19:06 UTC, DanteDeGrave commented on src/presenters/event-presenter.js
> +    if (this.#mode === 'EDITING') {
fixed

2021-12-14 19:06 UTC, DanteDeGrave commented on src/presenters/event-presenter.js
> +    this.#mode = 'DEFAULT';
fixed

2021-12-14 19:06 UTC, DanteDeGrave commented on src/utils/render.js
> +  if (component === null) {
fixed

2021-12-14 19:07 UTC, DanteDeGrave commented on src/view/site-info-view.js
> +  const amountTrip = points.reduce((acc, {price}) =>  acc + price, 0);
fixed

2021-12-15 08:29 UTC, maks88sgt approved these changes

2021-12-15 08:29 UTC, merged